FROM node:latest as builder
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY . ./
RUN npm run build

# production environment
FROM nginx:latest
COPY --from=builder /app/build /usr/share/nginx/html
CMD nginx -g 'daemon off;'
